export const HEADER_CONTROL_HEIGHT = 24
export const HEADER_CONTROL_RADIUS = 6
export const HEADER_CONTROL_FONT_SIZE = 11
export const HEADER_CONTROL_HORIZONTAL_PADDING = 8
export const HEADER_CONTROL_VERTICAL_PADDING = 0
export const HEADER_CONTROL_GAP = 4
export const HEADER_CONTROL_ROW_GAP = 4
