const defaultSetting: LX.AppSetting = {
  version: '2.1',
  'common.isAutoTheme': true,
  'common.langId': null,
  'common.apiSource': '',
  'common.sourceNameType': 'alias',
  'common.shareType': 'system',
  'common.isAgreePact': false,
  'common.autoHidePlayBar': true,
  'common.drawerLayoutPosition': 'left',
  'common.homePageScroll': true,
  'common.allowProgressBarSeek': true,
  'common.showBackBtn': false,
  'common.showExitBtn': true,
  'common.useSystemFileSelector': true,
  'common.alwaysKeepStatusbarHeight': false,

  'player.startupAutoPlay': false,
  'player.startupPushPlayDetailScreen': false,
  'player.togglePlayMethod': 'listLoop',
  'player.playQuality': '128k',
  'player.isSavePlayTime': false,
  'player.volume': 1,
  'player.playbackRate': 1,
  'player.cacheSize': '1024',
  'player.timeoutExit': '',
  'player.timeoutExitPlayed': true,
  'player.isAutoCleanPlayedList': false,
  'player.isHandleAudioFocus': true,
  'player.isEnableAudioOffload': true,
  'player.isShowLyricTranslation': false,
  'player.isShowLyricRoma': false,
  'player.isShowNotificationImage': true,
  'player.isS2t': false,
  'player.isShowBluetoothLyric': false,
  'player.isShowBluetoothFullLyric': false,

  // 'playDetail.isZoomActiveLrc': false,
  // 'playDetail.isShowLyricProgressSetting': false,
  'playDetail.style.align': 'center',
  'playDetail.vertical.style.lrcFontSize': 210,
  'playDetail.horizontal.style.lrcFontSize': 220,
  'playDetail.isShowLyricProgressSetting': false,

  'desktopLyric.enable': false,
  'desktopLyric.statusBarMode': false,
  'desktopLyric.isLock': false,
  'desktopLyric.width': 100,
  'desktopLyric.maxLineNum': 5,
  'desktopLyric.isSingleLine': false,
  'desktopLyric.showToggleAnima': true,
  'desktopLyric.position.x': 0,
  'desktopLyric.position.y': 0,
  'desktopLyric.textPosition.x': 'left',
  'desktopLyric.textPosition.y': 'top',
  'desktopLyric.style.fontSize': 180,
  'desktopLyric.style.opacity': 100,
  'desktopLyric.style.lyricUnplayColor': 'theme',
  'desktopLyric.style.lyricPlayedColor': 'theme',
  'desktopLyric.style.lyricShadowColor': 'rgba(0, 0, 0, 0.6)',
  'desktopLyric.style.backgroundColor': 'rgba(0, 0, 0, 0)',
  'desktopLyric.style.backgroundOpacity': 0,

  'statusBarLyric.enable': false,
  'statusBarLyric.isLock': true,
  'statusBarLyric.width': 52,
  'statusBarLyric.maxLineNum': 1,
  'statusBarLyric.isSingleLine': true,
  'statusBarLyric.showToggleAnima': false,
  'statusBarLyric.position.x': 24,
  'statusBarLyric.position.y': 0.6,
  'statusBarLyric.textPosition.x': 'center',
  'statusBarLyric.textPosition.y': 'center',
  'statusBarLyric.style.fontSize': 132,
  'statusBarLyric.style.opacity': 100,
  'statusBarLyric.style.lyricUnplayColor': 'rgba(255, 255, 255, 1)',
  'statusBarLyric.style.lyricPlayedColor': 'rgba(255, 255, 255, 1)',
  'statusBarLyric.style.lyricShadowColor': 'rgba(0, 0, 0, 0.5)',
  'statusBarLyric.style.backgroundColor': 'rgba(0, 0, 0, 1)',
  'statusBarLyric.style.backgroundOpacity': 42,

  'search.isShowHotSearch': true,
  'search.isShowHistorySearch': true,

  'list.isClickPlayList': false,
  'list.isShowSource': true,
  'list.isShowAlbumName': false,
  'list.isShowInterval': true,
  'list.isSaveScrollLocation': true,
  'list.addMusicLocationType': 'top',

  'download.fileName': '歌名 - 歌手',

  'sync.enable': false,

  'other.isEnableSyncLog': false,
  'other.isEnableUserApiLog': false,

  // 'theme.id': 'blue_plus',
  'theme.id': 'red',
  'theme.lightId': 'red',
  'theme.darkId': 'black',
  'theme.hideBgDark': false,
  'theme.dynamicBg': false,
  'theme.fontShadow': false,
}

export default defaultSetting
